#!/bin/bash
# (c) Copyright IBM Corp. 2016.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

SPARK_HOST=               # Spark Master hostname/ip
SPARK_PORT="7077"         # default spark master port
WORKBOOK_NAME="workbook"  # default workbook name
WORKBOOK_PORT="8888"      # default workbook port
