#!/bin/bash
# (c) Copyright IBM Corp. 2016.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

SPARK_HOST=${SPARK_HOST:=}
SPARK_PORT=${SPARK_PORT:=7077}
SPARK_CPUS=${SPARK_CPUS:=2}
SPARK_MEM=${SPARK_MEM:="1g"}
SPARK_USER=${SPARK_USER:="jovyan"}
WORKBOOK_NAME=${WORKBOOK_NAME:="workbook"}
WORKBOOK_PORT=${WORKBOOK_PORT:="8888"}
WORKBOOK_VOLUME=${WORKBOOK_VOLUME:="$WORKBOOK_NAME-vol"}
#WORKBOOK_DEBUG=${WORKBOOK_DEBUG:="--debug"}
